name: build-and-push
on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: clj-build
  GHR_TAG: ghcr.io/jarppe/$IMAGE_NAME
  HUB_TAG: jarppe/$IMAGE_NAME

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          cache-from: type=registry,ref=${GHR_TAG}:latest
          cache-to: type=inline
          tags: |
            ${GHR_TAG}:latest
            ${GHR_TAG}:${GITHUB_RUN_ID}
            ${HUB_TAG}:latest
            ${HUB_TAG}:${GITHUB_RUN_ID}
